// Industry-based form templates with pre-populated questions

export const INDUSTRIES = [
  { value: 'telecom', label: '📡 Telecommunications / Fibre' },
  { value: 'construction', label: '🏗️ Construction & Civil' },
  { value: 'electrical', label: '⚡ Electrical & Utilities' },
  { value: 'transport', label: '🚛 Transport & Logistics' },
  { value: 'mining', label: '⛏️ Mining & Resources' },
  { value: 'healthcare', label: '🏥 Healthcare & Aged Care' },
  { value: 'hospitality', label: '🍽️ Hospitality & Events' },
  { value: 'retail', label: '🛒 Retail & Warehousing' },
  { value: 'security', label: '🔒 Security Services' },
  { value: 'custom', label: '✏️ Start from scratch' },
];

function q(label, type = 'yes_no', options = []) {
  return { id: Date.now().toString() + Math.random(), label, type, required: true, options };
}

export const INDUSTRY_TEMPLATES = {
  telecom: {
    formType: 'prestart',
    description: 'Daily pre-start safety check for telecommunications and fibre technicians.',
    questions: [
      q('Are you fit for work today (no fatigue, illness or impairment)?'),
      q('Have you reviewed the job hazard assessment for today\'s site?'),
      q('Is your PPE (hard hat, hi-vis vest, gloves, safety boots) in good condition?'),
      q('Have you checked your tools and equipment are safe to use?'),
      q('Are you aware of any underground services or overhead power lines at the site?'),
      q('Have you completed a traffic management check if working near a road?'),
      q('Do you have a charged and working communication device?'),
      q('Any near misses or incidents to report from your last shift?'),
      q('I acknowledge I have read and understood today\'s safety briefing', 'signature'),
    ],
  },
  construction: {
    formType: 'prestart',
    description: 'Pre-start safety check for construction and civil works.',
    questions: [
      q('Are you free from fatigue, alcohol, or drugs that could affect your work?'),
      q('Have you completed a site induction or been briefed on site rules?'),
      q('Is your PPE (hard hat, hi-vis, safety boots, gloves, eye protection) worn and serviceable?'),
      q('Have you inspected your plant or equipment before use?'),
      q('Are exclusion zones and barricades correctly set up?'),
      q('Have you reviewed the SWMS/JSA for today\'s tasks?'),
      q('Is the weather suitable for the planned work activity?'),
      q('Are emergency evacuation routes and muster points known?'),
      q('Any hazards or unsafe conditions to report?', 'textarea'),
      q('I confirm I am fit for work and will comply with all site safety requirements', 'signature'),
    ],
  },
  electrical: {
    formType: 'prestart',
    description: 'Electrical and utilities pre-start safety declaration.',
    questions: [
      q('Are you licensed and authorised to carry out today\'s electrical work?'),
      q('Have you reviewed the job scope and identified all electrical hazards?'),
      q('Is lockout/tagout (LOTO) procedure confirmed for isolated equipment?'),
      q('Have you tested equipment with a voltage tester before commencing work?'),
      q('Is your PPE (insulated gloves, arc flash gear, safety glasses) serviceable?'),
      q('Are you working within your competency and licence conditions?'),
      q('Have you identified all underground cables and services?'),
      q('Is a safety observer or spotter in place for high-risk tasks?'),
      q('Any faults, near misses, or incidents to report?', 'textarea'),
      q('I declare I am fit for work and compliant with electrical safety regulations', 'signature'),
    ],
  },
  transport: {
    formType: 'prestart',
    description: 'Daily vehicle and driver pre-start check for transport and logistics.',
    questions: [
      q('Are you free from fatigue? (Have you had sufficient rest since last shift?)'),
      q('Do you hold a valid licence for the vehicle you will be operating today?'),
      q('Have you completed a walkaround vehicle inspection?'),
      q('Are tyres, lights, brakes, and mirrors in good working condition?'),
      q('Is the vehicle\'s load secured correctly?'),
      q('Are you familiar with today\'s route and any hazards?'),
      q('Do you have a charged mobile and emergency contact details?'),
      q('Vehicle condition', 'select', ['Good – no defects', 'Minor defect – reported', 'Major defect – not to be used']),
      q('Any vehicle damage or defects to report?', 'textarea'),
      q('I confirm I am fit to drive and the vehicle is roadworthy', 'signature'),
    ],
  },
  mining: {
    formType: 'prestart',
    description: 'Mining and resources site pre-start safety check.',
    questions: [
      q('Have you completed drug and alcohol testing as required?'),
      q('Are you free from fatigue and fit for your shift?'),
      q('Have you attended today\'s pre-shift toolbox talk?'),
      q('Is your PPE (hard hat, hi-vis, boots, gloves, ear and eye protection) serviceable?'),
      q('Have you reviewed the take 5 or hazard ID for your work area?'),
      q('Is your equipment pre-start check completed and recorded?'),
      q('Are you aware of all exclusion zones and blast areas?'),
      q('Do you know the emergency muster point and evacuation procedure?'),
      q('Any hazards, near misses, or incidents to report?', 'textarea'),
      q('I acknowledge today\'s safety requirements and will comply with site rules', 'signature'),
    ],
  },
  healthcare: {
    formType: 'prestart',
    description: 'Healthcare and aged care worker daily pre-start and wellness check.',
    questions: [
      q('Are you feeling well and free from illness or symptoms today?'),
      q('Have you had adequate rest (minimum 8 hours) since your last shift?'),
      q('Are you up to date with required vaccinations and health clearances?'),
      q('Do you have access to all required PPE (gloves, mask, apron) for your shift?'),
      q('Have you reviewed any updated care plans or client notes?'),
      q('Are you aware of any infection control alerts or isolation requirements?'),
      q('Do you know the emergency and escalation procedures for your ward/site?'),
      q('Any incidents, medication errors, or concerns to report from your last shift?', 'textarea'),
      q('I confirm I am fit for duty and will comply with infection control protocols', 'signature'),
    ],
  },
  hospitality: {
    formType: 'prestart',
    description: 'Pre-shift check for hospitality and events staff.',
    questions: [
      q('Are you fit for work today and free from illness?'),
      q('Have you reviewed today\'s event or service schedule?'),
      q('Is your uniform complete and presentation standards met?'),
      q('Have you completed required food handling and hygiene checks?'),
      q('Are all kitchen/service areas clean and hazard-free?'),
      q('Is fire safety equipment (extinguishers, exits) checked and accessible?'),
      q('Do you hold a current RSA certificate if serving alcohol?'),
      q('Any guest complaints, incidents, or maintenance issues to report?', 'textarea'),
      q('I confirm I am ready for my shift and will uphold service and safety standards', 'signature'),
    ],
  },
  retail: {
    formType: 'prestart',
    description: 'Retail and warehouse daily pre-start safety and operations check.',
    questions: [
      q('Are you fit for work and free from injury or illness?'),
      q('Have you been briefed on today\'s priorities and promotions?'),
      q('Are aisles, walkways, and emergency exits clear of obstructions?'),
      q('Have you inspected your workstation or area for hazards?'),
      q('Is your manual handling technique correct for today\'s tasks?'),
      q('Is PPE (steel-cap boots, hi-vis for warehouse) being worn?'),
      q('Are forklift and equipment licences valid for anyone operating today?'),
      q('Any stock discrepancies, incidents, or safety issues to report?', 'textarea'),
      q('I confirm I am ready for my shift and will follow all safety procedures', 'signature'),
    ],
  },
  security: {
    formType: 'prestart',
    description: 'Security officer daily pre-start check and briefing declaration.',
    questions: [
      q('Are you fit for duty and free from fatigue or impairment?'),
      q('Is your security licence current and carried on your person?'),
      q('Have you been briefed on today\'s site-specific instructions?'),
      q('Is your communication equipment (radio, phone) charged and working?'),
      q('Is your uniform and PPE complete and presentable?'),
      q('Have you reviewed any threat or incident alerts from the previous shift?'),
      q('Do you know the emergency procedures and escalation contacts for this site?'),
      q('Any incidents, suspicious activity, or concerns to report?', 'textarea'),
      q('I confirm I am fit for duty and have received today\'s briefing', 'signature'),
    ],
  },
  custom: {
    formType: 'prestart',
    description: '',
    questions: [],
  },
};